import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';

const timestamps = {
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at'),
};

export const sqliteSchema = {
  authProviderConfigs: sqliteTable('auth_provider_configs', {
    id: text('id').primaryKey(),
    key: text('key').notNull().unique(),
    kind: text('kind').notNull(),
    displayName: text('display_name').notNull(),
    issuer: text('issuer').notNull(),
    clientId: text('client_id').notNull(),
    clientSecretRef: text('client_secret_ref').notNull(),
    scopesJson: text('scopes_json').notNull(),
    configJson: text('config_json').notNull(),
    enabled: integer('enabled', { mode: 'boolean' }).notNull(),
    ...timestamps,
  }),
  authTransactions: sqliteTable('auth_transactions', {
    id: text('id').primaryKey(),
    providerKey: text('provider_key').notNull(),
    state: text('state').notNull().unique(),
    codeVerifier: text('code_verifier').notNull(),
    redirectTo: text('redirect_to'),
    workspaceHint: text('workspace_hint'),
    expiresAt: text('expires_at').notNull(),
    ...timestamps,
  }),
  users: sqliteTable('users', {
    id: text('id').primaryKey(),
    email: text('email').notNull().unique(),
    emailVerified: integer('email_verified', { mode: 'boolean' }).notNull(),
    displayName: text('display_name'),
    preferredUsername: text('preferred_username'),
    pictureUrl: text('picture_url'),
    ...timestamps,
  }),
  identities: sqliteTable('identities', {
    id: text('id').primaryKey(),
    userId: text('user_id').notNull(),
    providerKey: text('provider_key').notNull(),
    providerUserId: text('provider_user_id').notNull(),
    email: text('email'),
    claimsJson: text('claims_json'),
    claimsVersion: integer('claims_version'),
    ...timestamps,
  }),
  sessions: sqliteTable('sessions', {
    id: text('id').primaryKey(),
    userId: text('user_id').notNull(),
    providerKey: text('provider_key').notNull(),
    providerUserId: text('provider_user_id'),
    tokenHash: text('token_hash').notNull().unique(),
    activeWorkspaceId: text('active_workspace_id'),
    amrJson: text('amr_json').notNull(),
    expiresAt: text('expires_at').notNull(),
    lastSeenAt: text('last_seen_at').notNull(),
    ...timestamps,
  }),
  workspaces: sqliteTable('workspaces', {
    id: text('id').primaryKey(),
    slug: text('slug').notNull().unique(),
    name: text('name').notNull(),
    plan: text('plan').notNull(),
    ownerUserId: text('owner_user_id').notNull(),
    billingEmail: text('billing_email'),
    defaultAuthPolicyId: text('default_auth_policy_id'),
    archivedAt: text('archived_at'),
    ...timestamps,
  }),
  workspaceMemberships: sqliteTable('workspace_memberships', {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id').notNull(),
    userId: text('user_id').notNull(),
    role: text('role').notNull(),
    ...timestamps,
  }),
  projects: sqliteTable('projects', {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id').notNull(),
    slug: text('slug').notNull(),
    name: text('name').notNull(),
    archetype: text('archetype').notNull(),
    visibility: text('visibility').notNull(),
    hostingMode: text('hosting_mode').notNull(),
    defaultBranch: text('default_branch').notNull(),
    currentRevisionId: text('current_revision_id'),
    publishedDeploymentId: text('published_deployment_id'),
    archivedAt: text('archived_at'),
    ...timestamps,
  }),
  projectMemberships: sqliteTable('project_memberships', {
    id: text('id').primaryKey(),
    projectId: text('project_id').notNull(),
    userId: text('user_id').notNull(),
    role: text('role').notNull(),
    ...timestamps,
  }),
  projectManifests: sqliteTable('project_manifests', {
    id: text('id').primaryKey(),
    projectId: text('project_id').notNull(),
    revisionId: text('revision_id').notNull(),
    manifestJson: text('manifest_json').notNull(),
    manifestHash: text('manifest_hash').notNull(),
    ...timestamps,
  }),
  projectSiteContents: sqliteTable('project_site_contents', {
    id: text('id').primaryKey(),
    projectId: text('project_id').notNull(),
    revisionId: text('revision_id').notNull(),
    siteContentJson: text('site_content_json').notNull(),
    contentHash: text('content_hash').notNull(),
    ...timestamps,
  }),
  revisions: sqliteTable('revisions', {
    id: text('id').primaryKey(),
    projectId: text('project_id').notNull(),
    source: text('source').notNull(),
    actorUserId: text('actor_user_id').notNull(),
    baseRevisionId: text('base_revision_id'),
    status: text('status').notNull(),
    changeSummary: text('change_summary'),
    createdAt: text('created_at').notNull(),
  }),
  deployments: sqliteTable('deployments', {
    id: text('id').primaryKey(),
    projectId: text('project_id').notNull(),
    revisionId: text('revision_id').notNull(),
    environment: text('environment').notNull(),
    status: text('status').notNull(),
    staticUrl: text('static_url'),
    previewUrl: text('preview_url'),
    publishedUrl: text('published_url'),
    buildLogUrl: text('build_log_url'),
    buildArtifactPath: text('build_artifact_path'),
    startedAt: text('started_at'),
    completedAt: text('completed_at'),
    createdAt: text('created_at').notNull(),
  }),
  domains: sqliteTable('domains', {
    id: text('id').primaryKey(),
    projectId: text('project_id').notNull(),
    hostname: text('hostname').notNull().unique(),
    kind: text('kind').notNull(),
    verificationStatus: text('verification_status').notNull(),
    certificateStatus: text('certificate_status').notNull(),
    dnsTarget: text('dns_target'),
    isPrimary: integer('is_primary', { mode: 'boolean' }).notNull(),
    verificationToken: text('verification_token'),
    verifiedAt: text('verified_at'),
    createdAt: text('created_at').notNull(),
  }),
  assets: sqliteTable('assets', {
    id: text('id').primaryKey(),
    projectId: text('project_id').notNull(),
    kind: text('kind').notNull(),
    filename: text('filename').notNull(),
    mimeType: text('mime_type').notNull(),
    sizeBytes: integer('size_bytes').notNull(),
    sha256: text('sha256'),
    storageKey: text('storage_key'),
    publicUrl: text('public_url').notNull(),
    width: integer('width'),
    height: integer('height'),
    createdAt: text('created_at').notNull(),
  }),
  aiRequests: sqliteTable('ai_requests', {
    id: text('id').primaryKey(),
    projectId: text('project_id').notNull(),
    requestedByUserId: text('requested_by_user_id').notNull(),
    type: text('type').notNull(),
    status: text('status').notNull(),
    prompt: text('prompt').notNull(),
    scopeJson: text('scope_json').notNull(),
    inputRevisionId: text('input_revision_id'),
    outputRevisionId: text('output_revision_id'),
    summary: text('summary'),
    reviewRequired: integer('review_required', { mode: 'boolean' }).notNull(),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at'),
  }),
  jobRuns: sqliteTable('job_runs', {
    id: text('id').primaryKey(),
    jobType: text('job_type').notNull(),
    payloadJson: text('payload_json').notNull(),
    status: text('status').notNull(),
    attempts: integer('attempts').notNull(),
    errorSummary: text('error_summary'),
    availableAt: text('available_at').notNull(),
    startedAt: text('started_at'),
    completedAt: text('completed_at'),
    createdAt: text('created_at').notNull(),
  }),
};

export type SqliteSchema = typeof sqliteSchema;
